[dependencies]
anemoi-datasets = "==0.5.36"
cartopy = "*"
cftime = "*"
h5py = "*"
matplotlib = "*"
mlflow = "*"
netcdf4 = "*"
numcodecs = "*"
numpy = "*"
pandas = "<3.0"
pip = "*"
python = ">=3.13"
pytorch = "*"
pyyaml = "*"
scikit-learn = "*"
scipy = "*"
torch-geometric = "*"
torchvision = "*"
xarray = "*"
zarr = "<=2.18.7"

[environments]
default = {features = [], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}
docs = {features = ["docs"], solve-group = "default"}

[feature.dev.dependencies]
commitizen = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
ruff = "*"
types-markdown = ">=3.10.2.20260211,<4"
types-requests = ">=2.32.4.20260107,<3"

[feature.docs.dependencies]
myst-parser = ">=5.0.0,<6"
nbsphinx = ">=0.9.8,<0.10"
sphinx = ">=8.2.3,<9"
sphinx-autoapi = ">=3.6.1,<4"
sphinx-rtd-theme = ">=3.1.0,<4"

[feature.docs.tasks]
docs-build = "cp README.md docs/. && sed -i 's|docs/_static/logo.png|_static/logo.png|g' docs/README.md && cd docs && rm -fr _api && make clean && make html"

[pypi-dependencies]
d4p = {path = "./", editable = true}

[pypi-options]
index-url = "https://pypi.org/simple"

[tasks]
bumpversion-major = "cz bump --increment major"
bumpversion-minor = "cz bump --increment minor"
bumpversion-patch = "cz bump --increment patch"
default = {depends-on = ["qa", "type-check"]}
docker-build = "docker build -t d4p ."
docker-run = "docker run --rm -ti -v $(pwd):/srv d4p"
qa = "pre-commit run --all-files"
template-update = "pre-commit run --all-files cruft -c .pre-commit-config-cruft.yaml"
type-check = "python -m mypy ."

[workspace]
channels = ["conda-forge"]
name = "d4p"
platforms = ["linux-64"]
